# Generated by Django 3.2.7 on 2022-07-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='reaction',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
